### ISSUE TITLE
Client-side Gameguard folder causes client to stop at patch server

### ISSUE THREAD

**Issue by mfindlater** [dcrodman/archon#17]
Hi, a friend of mine was asking if it's possible to run a private pso server on a raspberry pi so I ended up discovering your repo here. I got as far as having the server running and connecting a client on localhost but I seem to be in a  open client - > patch update -> exit client loop. It is possible to get farther than that with the current commit to the character creator and ship list? (I know it's wip of course)? I know you made changes a few months ago.

**Comment by dcrodman** [comment]
Hey @mfindlater, you should be able to get as far as the ship/block list with Archon in its current form. What's in your patches directory (/usr/local/etc/archon/patches, unless you've changed it)? Also, what version of the client are you using?

**Comment by mfindlater** [comment]
I did change it (I'm on windows), here's the patches folder:
![image](https://user-images.githubusercontent.com/1313463/34805430-10bd829c-f64c-11e7-9e72-d2ca8d6427b2.png)

I'm using TethVer12513. I used the patcher from the tools folder.

**Comment by dcrodman** [comment]
That version should be fine. I've actually run into this issue before when I put the entire client in the patches folder, I vaguely recall there being something in the data subdirectory that was updated on every launch and caused the patch server to try to update it every time. What happens if you remove the data directory?

**Comment by mfindlater** [comment]
Turned out to be the GameGuard folder that did it. I got to the ship/block screen.

**Comment by dcrodman** [comment]
Cool. I should probably figure out a good way of getting Archon to warn if there are files present that trigger this behavior

**Comment by dcrodman** [comment]
Action item: patch server should ignore the Gameguard folder and warn if it's present
