### ISSUE TITLE
Soft delete characters when recreating

### ISSUE THREAD

**Issue by dcrodman** [dcrodman/archon#22]
The character server currently deletes `Character` rows during the recreate flow. It might cause a little data clutter in the long run but I'd like to change this to a soft delete model where none of the `Character` queries in the `data` package will include the "deleted" rows but the data isn't actually gone.

The main justification for this is that it might be helpful for server admins to be able to recover accounts that users have accidentally (or otherwise regret having) deleted.

**Comment by JNProtzman** [comment]
Since you have a deleted-at field in your Characters table, [you'll only be soft deleting](https://gorm.io/docs/delete.html#Soft-Delete).

**Comment by dcrodman** [comment]
Fixed by cc76d8420328c427e27439fd781bd50d572c057e
