### ISSUE TITLE
gRPC boilerplate for shipgate

### ISSUE THREAD

**Issue by dcrodman** [dcrodman/archon#24]
Add all of the boilerplate necessary to stand up protobuf services in the shipgate, generate X.509 certificates for ships, and generate shipgate client code.

**Comment by Sancaros** [comment]
will u pls put a demo show how to generate X.509 cert？ pls

**Comment by dcrodman** [comment]
Hi @Sancaros, the README has some instructions about how to use the generate_cert tool: https://github.com/dcrodman/archon#8-generate-the-shipgate-ssl-certificates

The jist is that you run that tool and provide it your server's external IP address (the one you'd provide to players who want to connect to your server). So for example if your server's host has an internal network address of 192.168.1.10 and you'd forwarded the requisite ports on your router to that host (the ones from [your config file](https://github.com/dcrodman/archon/blob/master/setup/config.yaml)), you'd take your router's external IP address (say 73.223.197.1) and use that as the input to generate_cert.
