### ISSUE TITLE
Client intermittently disconnects after character selection

### ISSUE THREAD

**Issue by dcrodman** [dcrodman/archon#26]
After selecting a character (during the second phase of the character server), the client disconnects and then reconnects to the character server. It then sends a login (0x93) packet and expects to receive a server timestamp, the ship list, and a scroll message in return. Most of the time this works fine and the client ends up at the ship selection screen.

However, sometimes the client never reconnects to the character server for this third phase. It either crashes during the burst screen or hangs before receiving the ship list. There doesn't seem to be any discernible pattern in what causes this to happen and Archon sends the exact same series of packets between working and non-working sessions. It also sends virtually identical packets (and in the same sequence) as tethealla.

Theories:
1. ~The server isn't disconnecting the client fast enough~ (closing the connection manually in response to the d/c packet has no discernible effect)
2. ~Sending packets to the packet analyzer is causing some sort of mayhem~ (this occurs with or without the packet analyzer integration)
3. ~Latency?~ (I'm ruling this out on the basis that the game supported slow connections)
4. Security packet contains some voodoo I haven't figured out (this seems unlikely since sylverant doesn't include the mysterious fixed bytes that tethealla uses)
5. ~Client is opening multiple connections to the server and is getting rejected by the connection uniqueness logic~ (no logs to indicate this and commenting out the code for sanity doesn't resolve the issue
6. Something around the connection management is wrong (at its core it's pretty simple and similar to tethealla. making each server single-threaded with one client at a time didn't fix it)

**Comment by dcrodman** [comment]
This was happening more intermittently before the major frontend refactoring (811e468), now it seems pretty steady

**Comment by Sancaros** [comment]
seems it still stock on no ship selecting

**Comment by dcrodman** [comment]
Fixed in 927481c9475ef455f68bc75c2ee7f3af1add96c2
