### ISSUE TITLE
Cannot build or run in Docker

### ISSUE THREAD

**Issue by PalasX** [dcrodman/archon#57]
Get these errors when trying to build/run in docker, with docker-compose.
docker build seems to work, but creates images with no label/tag?
![image](https://user-images.githubusercontent.com/37154966/166711240-57b900e4-c3f1-4593-820a-d50edc03b24a.png)
owner@laptopubuntu:~/docker/archon$ docker-compose build
ERROR: The Compose file is invalid because:
Service account has neither an image nor a build context specified. At least one must be provided.
owner@laptopubuntu:~/docker/archon$ docker-compose up -d
ERROR: The Compose file is invalid because:
Service account has neither an image nor a build context specified. At least one must be provided.

I'm assuming i'm doing something silly?

**Comment by dcrodman** [comment]
Hey @PalasX , sorry I only dug into this file recently myself and I know it used to work so I think there may have been some changes to docker-compose that this hasn't been kept up to date with. That is to say I'm sure you did nothing wrong, this setup just needed some attention.

I just pushed some fixes to this alongside a bundle of other changes, can you confirm whether or not this is now working for you?

**Comment by davidhaley** [comment]
I ran into an error with `docker-compose` as well:

`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 1: unknown instruction: DOCKERFILE`

![out](https://user-images.githubusercontent.com/11729897/170804699-8327795d-5741-42b7-bcb0-34ee2e64ef9e.png)

The solution for this error for me was to remove `Docker` from the Dockerfile:
![image](https://user-images.githubusercontent.com/11729897/170804705-db2357ae-0d0d-4325-97bc-21e7fd5469cd.png)

**Comment by davidhaley** [comment]
Posting this here for someone else. When I run `docker-compose`, the `postgres` container prematurely signals a healthy status, resulting in the other containers running, before it has a chance to create `archondb`.

![out](https://user-images.githubusercontent.com/11729897/170806184-5fd34370-f8a4-40ac-95de-e6e8aa6da723.png)

I following this (https://stackoverflow.com/a/16783253), I updated the postgres healthcheck test in `docker-compose.yml` from:

`test: [ "CMD-SHELL", "pg_isready -U archonadmin -d archondb" ]`

To:

`test: [ "CMD-SHELL", "pg_isready -U archonadmin -d archondb && psql -U -U archonadmin -lqt | cut -d \\| -f 1 | grep -qw archondb" ]`

And that seems to fix it:
![out](https://user-images.githubusercontent.com/11729897/170806390-1a8a1dbd-2a04-47fc-8999-59a0fbc81e75.png)


I'll figure out how to solve the next error: `archon-account-1          | 2022/05/28 02:32:58 /go/pkg/mod/gorm.io/driver/postgres@v1.0.8/migrator.go:130 ERROR: duplicate key value violates unique constraint "pg_class_relname_nsp_index" (SQLSTATE 23505)`

**Comment by dcrodman** [comment]
> The solution for this error for me was to remove Dockerfile from the Dockerfile

Wow well that one's delightful, no idea where that copy pasta came from. Just removed it. Also fixed the docker-compose setup, stumbled across what I'm guessing is the same recommendation https://newbedev.com/check-if-database-exists-in-postgresql-using-shell

> `ERROR: duplicate key value violates unique constraint`

That's been bugging me, I just pushed a fix for this

**Comment by dcrodman** [comment]
I'm hoping this has fixed things (it has on my machine™) but feel free to re-open if this still isn't working.

**Comment by PalasX** [comment]
no longer see dockerfile in repository. docker support abandoned?

**Comment by dcrodman** [comment]
Yep I removed the Dockerfile and docker-compose steps. Archon is significantly more self-contained now and should work out of the box without any other tools or setup, which is what the Docker Compose setup was originally there to facilitate. It also contains no platform-specific dependencies and with Go's dependency system able to keep builds consistent, having Docker in there seemed unnecessary (also given the nature of the project).
