### ISSUE TITLE
Account names with capital letters are not supported

### ISSUE THREAD

**Issue by davidhaley** [dcrodman/archon#58]
If I create an account that contains capitals (e.g. `CAPITALS`) and try to log in, I receive an RPC Error (account not found) on the client.

![image](https://user-images.githubusercontent.com/11729897/170812148-77eebe83-7cba-4e8c-bb89-2340a19aae6a.png)

**Comment by dcrodman** [comment]
That's a fun one, this is actually the PSOBB client. I'd forgotten that it did this but the client itself actually sends lowercase versions of the username, so there's not much I can do other than disallow the creation of usernames with capital letters to prevent this issue from occurring
