### ISSUE TITLE
Received unknown packets: 61, e7, 5

### ISSUE THREAD

**Issue by davidhaley** [dcrodman/archon#59]
After creating a character and logging in to the default ship.

![image](https://user-images.githubusercontent.com/11729897/170812216-08402d20-debf-409e-a826-1c82e3f0eaa0.png)

**Comment by dcrodman** [comment]
Hey @davidhaley, this is as far as the server is implemented so those missing packets are really just the "head" of work. I'm working on these now, but I typically don't keep issues around to represent that (otherwise I'd constantly be creating them).

**Comment by davidhaley** [comment]
Thanks @dcrodman!
