### ISSUE TITLE
Dreamcast suport

### ISSUE THREAD

**Issue by Gedehamsen021** [dcrodman/archon#60]
archon supports DC V2 version?

**Comment by Gurky-Kronos** [comment]
Also is this cross-platform, I know this isn't the place to ask but I don't know where to contact you outside of here.

**Comment by dcrodman** [comment]
> archon supports DC V2 version?

@Gedehamsen021, it doesn't currently support dreamcast and I don't have plans to add support. I'm not opposed to it in the long term, but I'm focusing on PSOBB before I worry about any other systems.

> Also is this cross-platform, I know this isn't the place to ask but I don't know where to contact you outside of here.

@Gurky-Kronos it should be, I generally test this on macOS and linux and people have found some minor Windows incompatibilities in the past. The cgo dependency it used to have is gone so as long as your system can compile Go (or you cross-compile for it) there shouldn't be any reason it isn't
