### ISSUE TITLE
Starting Question

### ISSUE THREAD

**Issue by chaosdrop** [dcrodman/archon#62]
Hi, I was wanting to introduce my nephew to PSOBB but he's young enough I don't want him playing on a public server and was thinking about running my own. 

I was wondering if this server is in a good state for that? In can't really find anything that says what is and isn't working.

It'll just be 3 people playing on the server so not much for load.

**Comment by dcrodman** [comment]
Hi @chaosdrop , love to hear that and I wish Archon was in a state where it could solve this for you. While I'm aiming to do a lot of work on it very soon, in the meantime I think your best bet is probably still to set up your own instance of Tethealla and run that: https://www.pioneer2.net/community/threads/tethealla-server-setup-instructions.1/

Sylverant and Newserv I believe are still targeted at Gamecube and have minimal PSOBB functionality, though you may want to take a look at those if you're so inclined. But for an intro to PSOBB, Tethealla ought to work just fine.

**Comment by chaosdrop** [comment]
Thanks for the info. I had wandered by Tethealla but it's public code seemed so abandoned I didn't know if it was really all that usable.

**Comment by dcrodman** [comment]
Yep, the open source version hasn't been updated in probably 10+ years so I understand the skepticism. But neither has the game client and while Tethealla definitely has its issues and is bare bones it's still amazingly functional. Hopefully at some point Archon will be competitive with the private server derivatives that are still around 🙂

**Comment by hortinstein** [comment]
Just wanted to say, I know how hard it is to find time to work on passion projects and this is impressive.  I am toying with the idea of using this server and others to write one in Nim.  Your code has been a great resource!  Wish you the best of luck!
